type = "agent"

[entrypoint]
prod = ".venv/bin/python3 -m src"
dev = "uv run uvicorn src.main:app --reload --port 1338 --host 0.0.0.0"

[[triggers]]
id = "slack-agent-public"
type = "http"
[triggers.configuration]
path = "agents/slack-agent"
authenticationType = "public"
